---
title: "Becoming a Data Analyst"
---

Two years ago, I found myself stuck and unhappy with my marketing career. I 
logged onto the US Labor of Statistics and reviewed every category of job listed.
I rated jobs by my level of interest and how much school I would need to complete
to switch into that industry. 

Maybe it was meant to be, given my data-driven and feature-engineeringapproach, 
that I found Data Science as the most interesting and practical path forward. 

In early 2017, I completed Calculus 1 and 2 to prepare for a Masters in Data 
Science. However, I started to wonder if I needed to complete a masters to join
the field. What if I didn't end up liking data science? 

I decided to change tactics and sign up for a Nanodegree through Udacity.com. 
Their Data Analyst program looked rigorous, with hands-on projects that I could 
use in my portfolio. I would gain hands-on experience quickly and affordably to 
help me assess my passion for the type of work. Learning sections included: 

* Inferential statistics
* Exploratory data analysis
* Cleaning messy data
* Introductory machine learning 
* Creating data stories in Tableau

I completed the program in February of 2018. In the meantime, I had successfully
argued for a full time Marketing Specialist to take over my marketing duties and
added a position for a Business Analyst / DAta Analyst. I'm now using R, building
dashboards, and migrating data as part of role. 

I am still building my skills through self-direct study. I've read several books
about R, Statistics, and data visualizations. DataFramed and Becoming a Data
Scientist are some of my favorite podcasts. And I'm enrolled for a fall 
Statistics class to deepend my basic understanding of statistics. 

Please reach out to me if you think I may be a good fit for your company or team!
